name: Build Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub registry
      uses: docker/login-action@v2
      with:
        username: dkhalife
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io

    - name: Build in the dev container
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/dkhalife/eclipse-mosquitto-with-auth
        cacheFrom: ghcr.io/dkhalife/eclipse-mosquitto-with-auth
        mounts: type=bind,source=${{ github.workspace }},target=/workspace
        runCmd: |
          cd src
          make clean
          make

    - name: Move built file
      run: |
        mv src/auth-plugin.so docker/

    - name: Azure Login with OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Log in to Azure Container Registry
      run: az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build and push
      run: |
        cd docker;
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/eclipse-mosquitto-with-auth:latest .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/eclipse-mosquitto-with-auth:latest
