name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make clean
      working-directory: ./src
      run: make clean
    - name: make
      working-directory: ./src
      run: make
