name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub registry
      uses: docker/login-action@v2
      with:
        username: dkhalife
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    - name: Pre-build image and run build in dev container
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/dkhalife/eclipse-mosquitto-with-auth
        cacheFrom: ghcr.io/dkhalife/eclipse-mosquitto-with-auth
        push: always
        runCmd: |
          cd src
          make clean
          make
