name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pre-build image and run build in dev container
      uses: devcontainers/ci@v0.3
      with:
        configFile: ../.devcontainer/devcontainer.json
        imageName: ghcr.io/dkhalife/eclipse-mosquitto-with-auth
        cacheFrom: ghcr.io/dkhalife/eclipse-mosquitto-with-auth
        push: always
        runCmd: |
          cd src
          make clean
          make
